### ISSUE TITLE
Thursday what a concept

### ISSUE THREAD

**Issue by Monimena** [YepesD/dias_bot#7]
### URL del meme

https://cdn.owo.cafe/cache/media_attachments/files/113/284/794/166/507/873/original/96b62347808dfb08.jpg

### Dia de la semana

Jueves

### Texto del toot

Thursday, what a concept

### Alt Text

Señora sonriente que sostiene un cigarro en la mano con el texto "Thursday. What a concept"

**Comment by YepesD** [comment]
🤙
