### ISSUE TITLE
Martes martes martes

### ISSUE THREAD

**Issue by Monimena** [YepesD/dias_bot#8]
### URL del meme

https://cdn.owo.cafe/media_attachments/files/113/627/405/066/844/246/small/0d9e68836bb0112a.jpg

### Dia de la semana

Martes

### Texto del toot

Martes martes martes

### Alt Text

Captura de pantalla de un artículo de la wikipedia titulado Martes martes martes.
El artículo dice: Martes martes martes es una subespecie de mamíferos carnívoros de la familia Mustelidae, subfamilia Mustelinae.
Tiene una imagen donde se ve al animal, se parece un poco a una comadreja.

**Comment by YepesD** [comment]
<3
